### ISSUE TITLE
(Possible) Issues Loading UMLS/SNOMEDCT_US w/LexEVS 6.2

### ISSUE THREAD

**Issue by mkitchin** [lexevs/lexevs#19]
Hi there,

I'm trying to load (what appears to be) the latest SNOMEDCT_US terminology via a UMLS subset and am getting pretty far in the process (8+hrs) before getting a great number of exceptions such as the one below.

In this case, I had to terminate the load after ~20hrs to make an appointment, so I can't say if it would've run to completion. At that point these exceptions had been coming steadily for ~8hrs.

Per another issue, I've updated UMLS_SAB_ISO_Map.txt to the set from master and that got me past an initial URN problem.

Configuration:
- 8 core (i7), 2.9GHz
- 16GB RAM, 8GB heap configured for libgui or loader script (tried both)
- SSD HD, plenty of space
- MySQL 5.5
- LexEVS 6.2 (release download)

Thoughts?

LB_WARN_LOGGER WARN - 2015-05-05 04:57:47,457 - [LOG_ID 26019] Error inserting Transitive closure item.
org.springframework.dao.DuplicateKeyException: SqlMapClient operation; SQL [];   
--- The error occurred in ibatis/v20/entityAssnsToEntity.xml.  
--- The error occurred while applying a parameter map.  
--- Check the Association.insertTransitiveClosure-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '360969006-SNOMED Clinical Terms US Edition-78548001-SNOMED Clini' for key 'lbaaapUQ_etet_stid'; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in ibatis/v20/entityAssnsToEntity.xml.  
--- The error occurred while applying a parameter map.  
--- Check the Association.insertTransitiveClosure-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '360969006-SNOMED Clinical Terms US Edition-78548001-SNOMED Clini' for key 'lbaaapUQ_etet_stid'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:241)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.insert(SqlMapClientTemplate.java:364)
	at org.lexevs.dao.database.ibatis.batch.SqlMapClientTemplateInserter.insert(SqlMapClientTemplateInserter.java:47)
	at org.lexevs.dao.database.ibatis.association.IbatisAssociationDao.doInsertIntoTransitiveClosure(IbatisAssociationDao.java:660)
	at org.lexevs.dao.database.ibatis.association.IbatisAssociationDao.insertIntoTransitiveClosure(IbatisAssociationDao.java:677)
	at org.lexevs.dao.database.ibatis.association.IbatisAssociationDao$$FastClassByCGLIB$$25bd0256.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
	at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
	at org.lexevs.dao.database.ibatis.association.IbatisAssociationDao$$EnhancerByCGLIB$$2d7f074f.insertIntoTransitiveClosure(<generated>)
	at org.lexevs.dao.database.operation.transitivity.DefaultTransitivityBuilder$BatchInsertController$3.execute(DefaultTransitivityBuilder.java:684)
	at org.lexevs.dao.database.service.daocallback.DaoManagerDaoCallbackService.executeInDaoLayer(DaoManagerDaoCallbackService.java:41)
	at org.lexevs.dao.database.service.daocallback.DaoManagerDaoCallbackService$$FastClassByCGLIB$$ea2683ff.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
	at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
	at org.lexevs.dao.database.service.daocallback.DaoManagerDaoCallbackService$$EnhancerByCGLIB$$c82b333.executeInDaoLayer(<generated>)
	at org.lexevs.dao.database.operation.transitivity.DefaultTransitivityBuilder$BatchInsertController.flush(DefaultTransitivityBuilder.java:680)
	at org.lexevs.dao.database.operation.transitivity.DefaultTransitivityBuilder$BatchInsertController.insertIntoTransitiveClosure(DefaultTransitivityBuilder.java:658)
	at org.lexevs.dao.database.operation.transitivity.DefaultTransitivityBuilder$BatchInsertController.access$300(DefaultTransitivityBuilder.java:620)
	at org.lexevs.dao.database.operation.transitivity.DefaultTransitivityBuilder.insertIntoTransitiveClosure(DefaultTransitivityBuilder.java:355)
	at org.lexevs.dao.database.operation.transitivity.DefaultTransitivityBuilder.processTransitive(DefaultTransitivityBuilder.java:297)
	at org.lexevs.dao.database.operation.transitivity.DefaultTransitivityBuilder.computeTransitivityTable(DefaultTransitivityBuilder.java:199)
	at org.lexevs.dao.database.operation.DefaultLexEvsDatabaseOperations.computeTransitiveTable(DefaultLexEvsDatabaseOperations.java:421)
	at org.lexgrid.loader.lexbigadmin.TransitivityBuildingTasklet.doExecute(TransitivityBuildingTasklet.java:68)
	at org.lexgrid.loader.lexbigadmin.AbstractLexEvsUtilityTasklet.execute(AbstractLexEvsUtilityTasklet.java:49)
	at org.lexgrid.loader.lexbigadmin.TransitivityBuildingTasklet.execute(TransitivityBuildingTasklet.java:47)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:347)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:261)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:76)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:367)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:214)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:143)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:247)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:196)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:115)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:61)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:124)
	at org.springframework.batch.core.job.flow.support.state.SplitState$1.call(SplitState.java:83)
	at org.springframework.batch.core.job.flow.support.state.SplitState$1.call(SplitState.java:81)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:229)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hsbauer** [comment]
Hi Michael:

You are right in thinking this should complete more quickly, but I’ll address that in a minute.  Your problem with exceptions is more concerning.  Normally I’d say that these kind of exceptions occur as a result of source data problems, but these appear to be occurring as a result of calculations that transitively connect values  so we could have an issue with the algorithm that provides that calculation.  If you have a way of looking at your database I’d suggest you provide me with the output of your coding scheme and registry tables.  I’d like a clearer idea as to what version we are looking at to see if someone has loaded it already.   There may also be a series of tables with upper case labels we use for staging that might be useful to look at.  

I’m also curious as to what MySQL drivers you have installed and what operating system you are running on.  This normally runs on my 4 core mac laptop with 16GB of RAM and an SSD in under eight  hours.

**Comment by mkitchin** [comment]
Hi there,

Thanks for getting back to me so quickly.

My guess is the long runtime is due to the exceptions -- judging from other imports, the process was approaching completion when they started.

MySQL details:
- Server: 5.5.43
- Driver: 5.1.35
- OS: Windows 7/Pro

Here's the list of tables with the expected prefix (lbaap in the GUI, still marked as "pending"):
![image](https://cloud.githubusercontent.com/assets/11393563/7476114/bf266712-f308-11e4-89bb-696d990e1611.png)

Thoughts?

**Comment by hsbauer** [comment]
I'd like to see the contents of lbaaapcodingscheme and anything similar to a table called lbregistry.  You might want to review our recommendations for MySQL for windows.  One setting in particular can really slow the windows version of MySQL down.  

https://wiki.nci.nih.gov/display/LexEVS/LexEVS+6.x+Local+Runtime+MySQL+Properties+Guide

It looks like the staging tables may be gone but they should have a slightly different prefix.

**Comment by mkitchin** [comment]
Hi there,

Here's the contents of lbaaapcodingscheme (one row):

# codingSchemeGuid, codingSchemeName, codingSchemeURI, representsVersion, formalName, defaultLanguage, approxNumConcepts, description, copyright, isActive, owner, status, effectiveDate, expirationDate, releaseGuid, entryStateGuid
'5562003', 'SNOMED Clinical Terms US Edition', 'urn:oid:2.16.840.1.113883.6.96', '2014_09_01', 'US Edition of SNOMED CT, 2014_09_01', 'ENG', NULL, 'International Health Terminology Standards Development Organization;SNOMED Clinical Terms US Edition;September 01, 2014;Copenhagen,Denmark;International Health Terminology Standards Development Organisation (IHTSDO)', 'NLM Customer service;NLM is a Charter Member of the IHTSDO on behalf of the U.S.;National Library of Medicine;8600 Rockville Pike;Bethesda;MD;United States;20894;1-888-FIND-NLM (1-888-346-3656);custserv@nlm.nih.gov', '1', NULL, NULL, NULL, NULL, NULL, '5562004'

Here's the related row in lbregistry:

# registryGuid, resourceURI, resourceVersion, resourceType, dbURI, dbName, prefix, stagingPrefix, status, tag, lastUpdateDate, activationDate, deactivationDate, baseRevision, fixedAtRevision, isLocked, dbSchemaVersion, dbSchemaDescription, supplementsUri, supplementsVersion
'8a896a454d1fd871014d2005795c0000', 'urn:oid:2.16.840.1.113883.6.96', '2014_09_01', 'CODING_SCHEME', NULL, NULL, 'aaap', 'lbaaao', 'pending', NULL, '2015-05-04 11:42:14', NULL, NULL, NULL, NULL, NULL, '2.0', 'LexGrid Table Schema Version 2.0', NULL, NULL

Noting the 'stagingPrefix' of 'lbaaao', there are these tables which appear to be the staging tables you referred to.
![image](https://cloud.githubusercontent.com/assets/11393563/7477694/bf97aee0-f312-11e4-8bec-4439bb302e93.png)

Would you like to see anything about these tables?

**Comment by hsbauer** [comment]
We've had issues with this version but they have been corrected in the version in the NCI Metathesaurus.    I can't tie these issues directly with what you have reported, but you can try downloading the NCI version of the Meta and subsetting from it: http://cbiit.nci.nih.gov/evs-download/metathesaurus-downloads.  This has been loaded successfully elsewhere although I haven't tried it myself.

**Comment by mkitchin** [comment]
Hi there,

Thanks for getting back to me so quickly, again.

Good news is I'm already importing the metathesaurus, so I ought to know in a few hours. I'll be sure to get back with you (here) about the results.

Out of curiosity, do you have a sense of when LexEVS 6.3 would be released?

**Comment by hsbauer** [comment]
We don’t have a release date for it as of yet.  It was not intended as a formal release and was slated to be folded into the 6.4 followup.  As such it’s something of a point release, but there are now plans to release it as a full release despite it’s limited scope.  Is there a particular feature you are interested in?

**Comment by mkitchin** [comment]
Hi there,

No specific features, no -- just getting conversant on the release timetable. Does 6.4 have a timeframe?

**Comment by hsbauer** [comment]
One of our roadmaps currently has us looking at next summer.  6.4 is a working version name at  the moment.  It's possible it could become a major release, but we don't know much more right now.  We have plans for background infrastructure upgrades.  Should be some performance enhancing changes, but not a lot new in the API or in the source loads we do after 6.3.

**Comment by mkitchin** [comment]
Hi there,

Good -- that's what I needed. Thanks for the update. I'll post back here when I have results from the metathesaurus load.

**Comment by hsbauer** [comment]
I've just had confirmation from one of the source curators that the UMLS version likely has some obsolete relationships that could cause the type of errors you were seeing. They might also cause a much larger and longer load time.

**Comment by mkitchin** [comment]
Hi there,

Thanks for looking into that. Do you know if this the sort of thing that's likely to be addressed in the UMLS or compensated for in some way by the software in the near future?

**Comment by hsbauer** [comment]
We will be talking about it soon.  Can’t make any promises but this seems like the kind of issue we'd like LexEVS to handle.  In the meantime, I’d stick with the NCI Metathesaurus sourced version.

**Comment by mkitchin** [comment]
Hi there,

Glad to hear it's under consideration. The metathesaurus sounds like the ticket, for now.

**Comment by mkitchin** [comment]
Hi there,

The NCI Metathesaurus (whole thing, not a subset) loaded with zero drama, once I made the MySQL/DB_URL changes for longer timeouts/auto-reconnect. Net time was ~14hrs.

As an aside: The MetaMorphoSys tool bundled with the Metathesaurus refused to start with an IndexOutOfBoundsException. I was able to get the MetaMorphoSys bundled with the UMLS to run, so it seems like something specific to the NCI bundle. I didn't bother subsetting the NCI Metathesaurus, anyway and have completed the import.

Do I need to do a separate MrMap import for vocabulary mappings, or was this implicit in the loader?

**Comment by hsbauer** [comment]
Micheal:

You'll have to take any issues with the MetaMorphSys tool up with the NLM folks.  You can run a load for an individual terminology against the entire Metathesaurus, but it is less performant than against a subsetted terminology.     

Our mapping API works against individually loaded maps and terminologies.  Having said that it is possible to discover inter terminology relationships within the Metathesaurus as loaded in LexEVS, but it may not be as transparent as the Mapping api.

**Comment by mkitchin** [comment]
Hi there,

Thanks for the quick response.

I should've been more specific -- should I run the mrmap loader against the mrmap file supplied with the nci metathesaurus to pick up the mappings, or was that step implicit in the nci metathesarus loader?

**Comment by hsbauer** [comment]
No problem.  You'll have to load MRMAP separately.  Loading MRMAP alone  will not allow complete mapping of relationships however -- you'll need to load the individual terminologies from the Meta in order to do that.

**Comment by mkitchin** [comment]
Hi there,

Thanks!

Sorry to be so obsessive, but I'm new to all this: Therefore, since I've not subsetted the Meta, I should have all the terminologies in place and only need to load the mrmap file?

**Comment by hsbauer** [comment]
Sorry, the terminologies will have to loaded separate from the Meta load.  You can load separate terminologies directly from the Meta RRF files or you can load from subsetted RRF files for each terminology.  You might pull your UMLS MetaMorphSys into the NCI Meta folder and see if it will subset it for you.  You loads will be faster that way.

**Comment by mkitchin** [comment]
Hi there,

Thanks for the extra detail -- Let's see if I have this correct:
- Loading the Meta (via MetaBatchLoader) imports all terminologies under one codesystem, however:
- Mappings (via MrMapLoader) are codesystem-to-codesystem, meaning:
- In order for mappings to resolve, we need to load the constituent codesystems, separately (via UMLSBatchLoader?)

**Comment by hsbauer** [comment]
That about covers it, yes.

**Comment by mkitchin** [comment]
Hi there,

Sweet :) Thanks for your help. I feel much more informed. I'll get to importing the terminologies and let you know if I have any concerns.

**Comment by rwynne** [comment]
Hi Micheal,

The MetaMorphoSys tool bundled with the RRF distribution has a slight packaging error that we will be fixing soon.

In the meantime, this is a simple one-line fix you can do on your end.  Open config/mmsys.prop, and modify the release_version property to read 201412 instead of 201406.  After saving this change, the tool should start without error.

Thank you for your interest in LexEVS and the NCI Metathesaurus.
